apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  namespace: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        resources:
          limits:
            memory: "1500Mi"
            cpu: 1
        ports:
        - containerPort: 5432
        env: 
        - name: POSTGRES_PASSWORD
          value: redhat123
