apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-app-datavol
  labels:
    app: postgres
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /share-data
    server: 172.31.40.140

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-app-data-0
  namespace: postgres
  labels:
    app: postgres
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    
