apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-store
  labels:
    app: nosql
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mydata/test
    server: 172.31.40.140

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-vol-1
  labels:
    app: mysql 
  namespace: mongo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
