apiVersion: v1
kind: Namespace
metadata:
  name: pod1example
  labels:
    app: example1 

--- 
apiVersion: v1
kind: Pod
metadata:
  name: pod1example-pod
  namespace: pod1example
  labels:
    app: example1
spec:
  containers:
  - name: pod1example-pod
    image: nginx:latest
    resources:
      requests: 
        cpu: "400m"
        memory: "600Mi"
      limits:
        memory: "900Mi"
        cpu: "900m"
    ports:
      - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: pod1example-pod-svc
  namespace: pod1example
  labels:
    app: example1
spec:
  selector:
    app: example1
  type: NodePort        # ClusterIP 
  ports:
  - name: example1-port
    port: 80
    targetPort: 80
    nodePort: 30002       # only add when nodeport service decleared 