apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-example1
  labels:
    name: nginx1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /apple
        backend:
          service:
            name: nginx1-svc
            port: 
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-example2
  namespace: mysql-server
  labels:
    app: database
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: phpmyadmin-svc
            port: 
              number: 80              