---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-vol-1
  labels:
    app: mysql 
  namespace: mongo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs-store
  accessModes:
    - ReadWriteOnce
